version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: recyclarr_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
    container_name: recyclarr_app_proxy_1

  server:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr_server_1
    user: 1000:1000
    volumes:
      - ${APP_DATA_DIR}data/config:/config
    environment:
      - TZ=America/Santiago
    ports:
      - "8787:8787"
    restart: on-failure
