version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: anunes-sonarr_server_1
      APP_PORT: 9090
      PROXY_AUTH_ADD: "false"
    container_name: anunes-sonarr_app_proxy_1

  server:
    image: lscr.io/linuxserver/sonarr:4.0.13@sha256:49a8e636fd4514b23d37c84660101fecbb632174ba0569e0f09bbd2659a2a925
    container_name: anunes-sonarr_server_1
    user: 1000:1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /mnt/anunes/downloads:/downloads
    restart: on-failure
